config/routes.rb
Rails.application.routes.draw do
  resources :products do 
    get "delete"
  end

  resources :attends do
    member do
      get 'export'
    end
  end

  resources :exams
  resources :patients
  resources :requesters
  resources :clinics
  get 'welcome/index'

  get "/qual_dia" => 'attends#diasel', as: 'qual_dia'

  get "/etiquetas" => 'attends#etiquetas'
  get "/print" => 'attends#print'

  devise_for :users, :path_prefix => 'my'
  resources :users

  root 'attends#index'

end

app/models/exam.rb
class Exam < ActiveRecord::Base
	has_and_belongs_to_many :attends
	validates :name, presence: true
	validates :name, uniqueness: true

	
	default_scope { order(name: :asc) }

end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: t('create_success') }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: t('update_success') }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: t('destroy_success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:name, :price)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= simple_form_for(@exam) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :label => t('name'), autofocus: true %>
  </div>

  <div class="actions text-right">
  		<%= link_to 'Cancelar', :back, :class => 'btn btn-default' %>
	  <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
	    <span class="glyphicon glyphicon-floppy-disk"></span> Salvar
	  <% end %>
  </div>
<% end %>

app/views/exams/edit.html.erb
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
      <h2>Editar <%= t("exam") %></h2>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <div class="text-right">
        <h2>
		  <%= link_to exams_path, :class => 'btn btn-primary' do %>
		    <span class="glyphicon glyphicon-chevron-left"></span> Voltar
		  <% end %> 
		  <%= link_to exam_path(@exam), method: :delete, :class => 'btn btn-danger', data: { confirm: t('Are you sure?')  } do %>
		    <span class="glyphicon glyphicon-remove"></span> Apagar
		  <% end %> 
        </h2>
      </div>
    </div>
  </div> <!-- /.row -->
<%= render 'form' %>

app/views/exams/index.html.erb
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
      <h2><%= t("exams") %></h2>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <div class="text-right">
        <h2>
          <%= link_to new_exam_path, :class => 'btn btn-primary' do %>
            <span class="glyphicon glyphicon-plus"></span> Adicionar
          <% end %>
        </h2>
      </div>
    </div>
  </div> <!-- /.row -->
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('name') %></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= link_to exam.name, exam %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/exams/new.html.erb
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
      <h2><%= t("New") %> <%= t("exam") %></h2>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <div class="text-right">
        <h2>
		  <%= link_to exams_path, :class => 'btn btn-primary' do %>
		    <span class="glyphicon glyphicon-chevron-left"></span> Voltar
		  <% end %> 
        </h2>
      </div>
    </div>
  </div> <!-- /.row -->
<%= render 'form' %>

app/views/exams/show.html.erb
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
      <h2><%= @exam.name %></h2>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <div class="text-right">
        <h2>
          <%= link_to exams_path, :class => 'btn btn-primary' do %>
            <span class="glyphicon glyphicon-chevron-left"></span> Voltar
          <% end %> 
          <%= link_to edit_exam_path(@exam), :class => 'btn btn-success' do %>
            <span class="glyphicon glyphicon-list-alt"></span> Editar
          <% end %> 
          <%= link_to exam_path(@exam), method: :delete, :class => 'btn btn-danger', data: { confirm: t('Are you sure?')  } do %>
            <span class="glyphicon glyphicon-remove"></span> Apagar
          <% end %> 
        </h2>
      </div>
    </div>
  </div> <!-- /.row -->
    <div class="panel panel-default">
      <div class="panel-body">
        <p>
          <strong><%= t("name") %>:</strong>
          <%= @exam.name %>
        </p>
      </div><!-- /panel-body -->
    </div><!-- /panel -->