config/routes.rb
Rails.application.routes.draw do
  resources :products do 
    get "delete"
  end

  resources :attends do
    member do
      get 'export'
    end
  end

  resources :exams
  resources :patients
  resources :requesters
  resources :clinics
  get 'welcome/index'

  get "/qual_dia" => 'attends#diasel', as: 'qual_dia'

  get "/etiquetas" => 'attends#etiquetas'
  get "/print" => 'attends#print'

  devise_for :users, :path_prefix => 'my'
  resources :users

  root 'attends#index'

end

app/models/attend.rb
class Attend < ActiveRecord::Base
  belongs_to :clinic
  belongs_to :patient
  belongs_to :requester
  has_and_belongs_to_many :exam

  validates :requester_id, :clinic_id, :appointment, :schedule, :descriptive, presence: true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "sem-imagem.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  #validates_attachment_size :avatar, size: { in: 0..10.kilobytes }

  ##default_scope { order(appointment: :asc) }

  scope :para_o_dia, -> (dia) { where schedule: dia }
  scope :para_a_clinica, -> (clinica) { where clinic_id: clinica }
  scope :quais, -> (selecionadas) { where id: selecionadas }


  #scope :four_last, -> { order("products.updated_at DESC LIMIT 4") }

  # simple_calendar find column "start_time". Here set a nickname
  def start_time
        self.schedule
  end

    #scope :clinic, -> (clinic_id) { where clinic_id: clinic_id }
end

app/models/exam.rb
class Exam < ActiveRecord::Base
	has_and_belongs_to_many :attends
	validates :name, presence: true
	validates :name, uniqueness: true

	
	default_scope { order(name: :asc) }

end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController
  before_action :set_attend, only: [:show, :edit, :update, :destroy, :export]
  load_and_authorize_resource

   # Nós incluimos aqui a lib que vamos criar chamada generate_pdf.rb
  require './lib/generate_pdf'

  def diasel
    #render text: "Action diasel"
    @attends = Attend.where(nil)
    #@attends = Attend.where("clinic_id = ?", current_user.clinic_id)
    #@attends = @attends.para_o_dia(params[:dia]) if params[:dia].present?
    ##if params[:dia].present?
    ##  @attends = @attends.para_a_clinica(current_user.clinic_id).para_o_dia(params[:dia])
    ## else
    ##  @attends = @attends.para_a_clinica(current_user.clinic_id).para_o_dia(Date.current)
    ##end

    @attends = @attends.para_a_clinica(current_user.clinic_id).para_o_dia(params[:dia])
    respond_to do |format|
      format.js
    end
  end

  # GET /attends
  # GET /attends.json
  def index
    @attend = Attend.new

    if params[:dia].present?
      @attend.schedule = params[:dia]
    else
      @attend.schedule = Date.current
    end

    if params[:start_date].present?
      mes_para_consulta = params[:start_date].to_date
    else
      mes_para_consulta = Date.current
    end

    beginning_of_month = mes_para_consulta.beginning_of_month
    end_of_month = beginning_of_month.end_of_month

    @attends_todos = Attend.where(schedule: beginning_of_month..end_of_month)
    @attends_todos = @attends_todos.para_a_clinica(current_user.clinic_id)


    @attends = Attend.where(nil)
    #@attends = @attends.para_a_clinica(current_user.clinic_id)
    @attends = @attends.para_a_clinica(current_user.clinic_id).para_o_dia(Date.current).order(appointment: :asc)
    #filtro, usa scope no model - desativado por enquanto
    #@attends = @attends.clinic(params[:clinic]) if params[:clinic].present?

    @aniversariantes = Patient.aniversariantes
  end

  # GET /attends/1
  # GET /attends/1.json
  def show
  end

  # GET /attends/new
  def new
    @attend = Attend.new

    if params[:dia].present?
      @attend.schedule = params[:dia]
    else
      @attend.schedule = Date.current
    end

    if params[:hora].present?
      @attend.appointment = params[:hora]
    end


    @attends_todos = Attend.where(nil)
    @attends_todos = @attends_todos.para_a_clinica(current_user.clinic_id)

    @attends = Attend.where(nil)
    @attends = @attends.para_a_clinica(current_user.clinic_id).para_o_dia(Date.current)
  end

  # GET /attends/1/edit
  def edit
  end

  # POST /attends
  # POST /attends.json
  def create
    @attend = Attend.new(attend_params)
    @attend.clinic_id = current_user.clinic_id

    #year_of_birth_date = @attend.patient.birth_date.strftime("%Y").to_i
    #year_of_today = Date.today.strftime("%Y").to_i
    #@attend.age = year_of_today - year_of_birth_date

    @attends_todos = Attend.where(nil)
    @attends_todos = @attends_todos.para_a_clinica(current_user.clinic_id)

    @attends = Attend.where(nil)
    @attends = @attends.para_a_clinica(current_user.clinic_id).para_o_dia(Date.current)


    respond_to do |format|
      if @attend.save
        format.html { redirect_to @attend, notice: t('create_success') }
        format.json { render :show, status: :created, location: @attend }
        #format.js   {render :show, status: :created, location: @attend }
      else
        format.html { render :new }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
        #format.js {render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attends/1
  # PATCH/PUT /attends/1.json
  def update

    if @attend.patient.present?
      year_of_birth_date = @attend.patient.birth_date.strftime("%Y").to_i
      year_of_today = Date.today.strftime("%Y").to_i
      @attend.age = year_of_today - year_of_birth_date
    end

    respond_to do |format|
      if @attend.update(attend_params)

        format.html { redirect_to @attend, notice: t('update_success') }
        format.json { render :show, status: :ok, location: @attend }
      else
        format.html { render :edit }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attends/1
  # DELETE /attends/1.json
  def destroy
    @attend.destroy
    respond_to do |format|
      format.html { redirect_to attends_url, notice: t('destroy_success') }
      format.json { head :no_content }
    end
  end

    # Criamos este método que vai chamar nossa lib para gerar o PDF e depois redirecionar o user para o arquivo PDF
  def export
    #pasta-folha, pasta-etiqueta, caixa-normal, caixa-economica
    modelo_etiqueta = params[:modelo]

    modelo = case modelo_etiqueta
    when "pasta-folha" then
      ##GeneratePdf::attend_pasta_folha(@attend.schedule, @attend.appointment, @attend.patient.name)
      GeneratePdf::attend_pasta_folha(@attend)
      redirect_to '/pasta-folha.pdf'
      puts "pasta-folha"
    when "pasta-etiqueta" then
      GeneratePdf::attend_pasta_etiqueta(@attend)
      redirect_to '/pasta-etiqueta.pdf'
      puts "pasta-etiqueta"
    when "caixa-normal" then
      GeneratePdf::attend_caixa_normal(@attend)
      redirect_to '/caixa-normal.pdf'
      puts "caixa-normal"
    when "caixa-economica" then
      GeneratePdf::attend_caixa_economica(@attend)
      redirect_to '/caixa-economica.pdf'
      puts "caixa-economica"
    end
  end

  def etiquetas
    @attends = Attend.all
    @attends = @attends.para_a_clinica(current_user.clinic_id).order(schedule: :desc)
  end

  def print
    @attends = Attend.where(nil)
    @teste = params[:attend]
    atendimentos_selecionados = @teste[:attend_ids]
    @attends_selected = @attends.quais(atendimentos_selecionados)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attend
      @attend = Attend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attend_params
      params.require(:attend).permit(:avatar, :clinic_id, :age, :patient_id, :schedule, :appointment, :requester_id, :notes, :discount, :total, :descriptive, :finalized, :missed, :exam_ids => [])
    end
end

app/helpers/attends_helper.rb
module AttendsHelper
	#Just experiments
  def dia_selected
    if params[:dia].present?
      return Date.parse(params[:dia])
    else
      return Date.current
    end
  end

  def apontamento(hora)
    hora = hora
    @atendimentos = @attends.where appointment: hora
    if (@atendimentos.length != 0)
      concatenada = ""
      @atendimentos.each do |consulta|
        if consulta.finalized == true
          concatenada << link_to("<span class='glyphicon glyphicon-check'></span> #{consulta.descriptive}".html_safe, consulta, class: "btn btn-success btn-xs margem-btn")
        else
          concatenada << link_to("<span class='glyphicon glyphicon-time'></span> #{consulta.descriptive}".html_safe, consulta, class: "btn btn-warning btn-xs margem-btn")
        end
        concatenada << " "        
      end
      ##Mostrar botao para adicionar mais um agendamento para o mesmo horario
      concatenada << link_to("<span class='glyphicon glyphicon-plus'></span>".html_safe, new_attend_path(:dia => dia_selected, :hora => hora), class: "btn btn-primary btn-xs margem-btn")
      
      return  "<span class='badge'>#{hora}</span> #{concatenada}".html_safe

      ##return "aqui tem #{@atendimentos.length} - #{concatenada}".html_safe + " <span class='badge'>#{hora}</span>".html_safe
    else
      return link_to("<span class='glyphicon glyphicon-calendar'></span>  <span class='glyphicon glyphicon-plus'></span>".html_safe, new_attend_path(:dia => dia_selected, :hora => hora), class: "btn btn-primary btn-xs") + " <span class='badge'>#{hora}</span>".html_safe
    end
  end

  #def apontamento(hora)
  #  @hora = hora
  #  consulta = @attends.find_by appointment: @hora
  #  if (consulta)
  #    if consulta.finalized == true
  #      return link_to "<span class='glyphicon glyphicon-check'></span> <span class='badge'>#{@hora}</span> #{consulta.patient.name}".html_safe, consulta, :class => "list-group-item list-group-item-action links-listagem list-group-item-info"
  #    else
  #      return link_to "<span class='glyphicon glyphicon-time'></span> <span class='badge'>#{@hora}</span> #{consulta.patient.name}".html_safe, consulta, :class => "list-group-item list-group-item-action links-listagem"      
  #    end
  #    
  #  else
  #    return link_to "<span class='glyphicon glyphicon-calendar'></span> <span class='badge'>#{@hora}</span> ...".html_safe, new_attend_path(:dia => dia_selected, :hora => @hora), :class => "list-group-item list-group-item-action links-listagem"
  #  end
  #end



	 def myclinic
    	render :text => current_user.clinic.fantasy_name
  	end

    def my_clinic_id
      return current_user.clinic.id
    end

  	def my_clinic_attends
  		my_attends  = Attends.all
  	end

  	def my_formatted_number number
    	number_to_currency(number, separator: ",", delimiter: "", format: '%n')
  	end

    def events_ajax_previous_link
      ->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, :remote => true}
    end

    def events_ajax_next_link
      ->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last + 1.day}, :remote => true}
    end

end

app/views/attends/_attend.html.erb
<%= attend.id %>

app/views/attends/_attend_detalhe.html.erb
<!-- Modal -->
	<div class="modal-dialog modal-lg" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="modal_label_listagem"><%= @attend.appointment.strftime("%H:%M") %> - <%= @attend.patient.name %></h4>
	      </div>
	      <div class="modal-body">	        
			<p>
			  <strong><%= t('gender') %>:</strong>
			  <%= @attend.patient.gender %>
			  <strong><%= t('birth_date') %>:</strong>
			  <%= @attend.patient.birth_date.strftime("%d/%m/%Y") %>
			</p>
			<p>
			  <strong><%= t('exams') %>:</strong>
			  <ul>
			  <% @attend.exam.each do |exame| %>
			    <li><%= exame.name %></li>
			  <% end %>
			  </ul>
			</p>
			<p>
			  <strong><%= t('requester') %>:</strong>
			  <%= @attend.requester.name %>
			</p>					
			<p>
			  <strong><%= t('rg') %>:</strong>
			  <%= @attend.patient.rg %>
			</p>		  			
			<p>
			  <strong><%= t('cpf') %>:</strong>
			  <%= @attend.patient.cpf %>
			</p>		  			
			<p>
			  <strong><%= t('address') %>:</strong>
			  <%= @attend.patient.address %> <%= @attend.patient.city %> <%= @attend.patient.province.acronym %>
			</p>	  			
			<p>
			  <strong><%= t('email') %>:</strong>
			  <%= @attend.patient.email %>
			</p>		  			
		
			<p>
			  <strong><%= t('phone') %>:</strong>
			  <%= @attend.patient.phone %>. <%= @attend.patient.phone2 %>
			</p>
			<p>
			  <strong><%= t('payment_detail') %>:</strong>
			  <%= @attend.payment_detail %>
			</p>

			<p>
			  <strong><%= t('finalized') %>:</strong>
			  <%= human_boolean(@attend.finalized) %>
			</p>

			<p>
			  <strong><%= t('missed') %>:</strong>
			  <%= human_boolean(@attend.missed) %>
			</p>

			<p>
			  <strong><%= t('notes') %>:</strong>
			  <%= @attend.notes %>
			</p>
	      </div>
	      <div class="modal-footer">
	      	<%= link_to "Editar", edit_attend_path(@attend), :class => "btn btn-info", remote: true %>
	        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
	      </div>
	    </div>
	</div><!-- /.modal-dialog -->

app/views/attends/_calendar.html (cópia).erb
<%= month_calendar events: attends, previous_link: events_ajax_previous_link, next_link: events_ajax_next_link do |date, attend| %>
	<%= link_to qual_dia_path(:dia => date), :remote => true, :onclick => "this.style.backgroundColor='#990000'" do %>
    <strong><%= date.day %></strong>
  <% end %>
  <% if attend.length != 0 %>
     <div class="text-right num-attends"><%= attend.length %></div>
  <% end %>
<% end %>


<%= week_calendar events: attends, previous_link: events_ajax_previous_link, next_link: events_ajax_next_link do |date, attend| %>
	<%= link_to qual_dia_path(:dia => date), :remote => true, :onclick => "this.style.backgroundColor='#990000'" do %>
    <strong><%= date.day %></strong>
  <% end %>
  <% if attend.length != 0 %>
     <div class="text-right num-attends"><%= attend.length %></div>
  <% end %>
<% end %>

<%= calendar events: attends, previous_link: events_ajax_previous_link, next_link: events_ajax_next_link do |date, attend| %>
	<%= link_to qual_dia_path(:dia => date), :remote => true, :onclick => "this.style.backgroundColor='#990000'" do %>
    <strong><%= date.day %></strong>
  <% end %>
  <% if attend.length != 0 %>
     <div class="text-right num-attends"><%= attend.length %></div>
  <% end %>
<% end %>

app/views/attends/_calendar_semanal.html (cópia).erb
<%= week_calendar events: attends, previous_link: events_ajax_previous_link, next_link: events_ajax_next_link do |data, attends| %>

<div class="list-group">
<% attends.each do |attend| %>
	<a href="#modal_<%= attend.id %>" class="list-group-item" data-toggle="modal"><small><strong><%= attend.appointment.strftime("%H:%M") %></strong><br><%= attend.patient.name %></small></a>
		<!-- Modal -->
			<div class="modal fade" id="modal_<%= attend.id %>" tabindex="-1" role="dialog" aria-labelledby="modal_<%= attend.id %>">
			  <div class="modal-dialog modal-lg" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="modal_label_<%= attend.id %>"><%= attend.appointment.strftime("%H:%M") %> - <%= attend.patient.name %></h4>
			      </div>
			      <div class="modal-body">	        
					<p>
					  <strong><%= t('gender') %>:</strong>
					  <%= attend.patient.gender %>
					  <strong><%= t('birth_date') %>:</strong>
					  <%= attend.patient.birth_date %>
					</p>
					<p>
					  <strong><%= t('exams') %>:</strong>
					  <ul>
					  <% attend.exam.each do |exame| %>
					    <li><%= exame.name %></li>
					  <% end %>
					  </ul>
					</p>
					<p>
					  <strong><%= t('requester') %>:</strong>
					  <%= attend.requester.name %>
					</p>					
					<p>
					  <strong><%= t('rg') %>:</strong>
					  <%= attend.patient.rg %>
					</p>		  			
					<p>
					  <strong><%= t('cpf') %>:</strong>
					  <%= attend.patient.cpf %>
					</p>		  			
					<p>
					  <strong><%= t('address') %>:</strong>
					  <%= attend.patient.address %> <%= attend.patient.city %> <%= attend.patient.province.acronym %>
					</p>	  			
					<p>
					  <strong><%= t('email') %>:</strong>
					  <%= attend.patient.email %>
					</p>		  			
  			
					<p>
					  <strong><%= t('phone') %>:</strong>
					  <%= attend.patient.phone %>. <%= attend.patient.phone2 %>
					</p>
					<p>
					  <strong><%= t('payment_detail') %>:</strong>
					  <%= attend.payment_detail %>
					</p>

					<p>
					  <strong><%= t('finalized') %>:</strong>
					  <%= human_boolean(attend.finalized) %>
					</p>

					<p>
					  <strong><%= t('missed') %>:</strong>
					  <%= human_boolean(attend.missed) %>
					</p>

					<p>
					  <strong><%= t('notes') %>:</strong>
					  <%= attend.notes %>
					</p>
			      </div>
			      <div class="modal-footer">
			        <%= link_to "Editar", edit_attend_path(attend), :class => "btn btn-info" %>		      
			        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
			      </div>
			    </div>
			  </div>
			</div><!-- /.modal -->

<% end %>
</div><!-- /.list-group -->


<% end %>

app/views/attends/_edit_modal.html.erb
<!-- Modal -->
  <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="modal_label_listagem"><%= t('Edit') %> <%= t('attend') %></h4>
        </div>
        <div class="modal-body">          
          <div id="formulario" >
            <%= render partial: "form" %>
          </div><!-- /formulario-->
        </div>
        <div class="modal-footer">
              <%= link_to attend_path(@attend), method: :delete, :class => 'btn btn-danger', data: { confirm: t('Are you sure?')  } do %>
                <span class="glyphicon glyphicon-remove"></span> Apagar
              <% end %> 
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        </div><!-- /modal-footer-->
      </div><!-- /modal-content-->
  </div><!-- /.modal-dialog -->

app/views/attends/_form.html (cópia).erb
<h3>Dia <%=l dia_selected, format: :long %></h3>
<h4><%= myclinic %></h4>


<%
commentario = "f.association :clinic, :label => t('clinic'), label_method: :fantasy_name, value_method: :id, prompt: t('select') "
comentario2 = "f.input :schedule, :label => t('schedule'), :as => :date_picker "
%>

<div class="row">
  <div class="col-lg-4">
      <div id="events_calendar">
        <%= render partial: "calendar", locals: {attends: @attends_todos} %>
      </div><!-- /events_calendar -->
  </div><!-- /col -->
  <div class="col-lg-4">
    <div id="lista-horarios">
    <%= render partial: "listagem", locals: {attends: @attends} %>
    </div><!-- /lista-horarios -->
  </div><!-- /col -->
  <div class="col-lg-4">
    <div id="cliente-atendimento">
         <%= simple_form_for(@attend) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
     
    <% comentario4 = "f.hidden_field :clinic_id, value: my_clinic_id " %>
    <% comentario3 = "f.hidden_field :schedule, value: dia_selected" %>

    <% comentario5 = "f.input :schedule, :as => :hidden, :input_html => { :value => dia_selected } " %>

    <%= f.input :patient_id, :label => t('patient') %>
    <%= f.input :schedule, :label => t('schedule'), :as => :date_picker %>
    <%= f.input :appointment, :label => t('appointment'),:as => :time_picker %>
    <%= f.association :exam, :label => t('exams'), as: :check_boxes %>
    <%= f.association :requester, :label => t('requester'), prompt: t('select') %>
    <%= f.input :payment_detail, :label => t('payment_detail') %>
    <%= f.input :finalized, :label => t('finalized') %>
    <%= f.input :missed, :label => t('missed') %>
    <%= f.input :notes, :label => t('notes') %>
  </div>
<div class="actions text-right">
      <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
        <span class="glyphicon glyphicon-floppy-disk"></span> Salvar
      <% end %>
  </div>
<% end %>
     


    </div><!-- /cadastra-ainda-nao-ta-usando -->
  </div><!-- /col -->  
</div><!-- /row -->

app/views/attends/_form.html.erb
<%= simple_form_for(@attend) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
      <div class="form-group">
        <%= link_to patients_path, remote: true, class: "btn btn-success" do %>
          <span class="glyphicon glyphicon-lock" aria-hidden="true"> </span> Vincular ao Cadastro de Pacientes
        <% end %>
      </div>
    <%= f.input :descriptive, :label => t('descriptive'), autofocus: true %>
    <%= f.input :schedule, :label => t('schedule'), :as => :date_picker %>
    <%= f.input :appointment, :label => t('appointment'), :as => :time_picker, :hint => "De 15 em 15 minutos dentro do horário de atendimento"  %>

    <%= f.hidden_field :patient_id %>

    <div class="panel panel-default">
      <div class="panel-body">
        <%= image_tag @attend.avatar.url(:thumb), :class => "img-thumbnail" if @attend.avatar.exists? %>
        <%= f.input :avatar, :label => t('avatar'), as: :file %>
      </div><!-- /panel-body -->
    </div><!-- /panel -->


    <%= f.association :requester, :label => t('requester'), prompt: t('select'), :id => "select-search", collection: Requester.order('name ASC') %>
    <%= f.association :exam, :label => t('exams'), as: :check_boxes %>
    <%= f.input :notes, :label => t('notes') %>
    <%= f.input :finalized, :label => t('finalized')+"?" %>
  </div><!-- /form-inputs -->
  <div class="actions text-right">
      <%= link_to 'Cancelar', :back, :class => 'btn btn-default' %>
      <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
        <span class="glyphicon glyphicon-floppy-disk"></span> Salvar
      <% end %>
  </div>
<% end %>
<div class="modal fade" id="patient-modal"></div>
<div class="modal fade" id="patient-new-modal"></div>

app/views/attends/_listagem.html.erb
  <h2><%= l(dia_selected, format: '%A, %d de %B de %Y') %></h2>
	<div class="row">
		<div class="col-lg-6 col-md-6">
			<ul class="list-group">			
        <li class="list-group-item disabled"><strong>MANHÃ</strong></li>
        <li class="list-group-item"><%= apontamento("07:30") %></li>
        <li class="list-group-item"><%= apontamento("07:45") %></li>
				<li class="list-group-item"><%= apontamento("08:00") %></li>
				<li class="list-group-item"><%= apontamento("08:15") %></li>
				<li class="list-group-item"><%= apontamento("08:30") %></li>
				<li class="list-group-item"><%= apontamento("08:45") %></li>
				<li class="list-group-item"><%= apontamento("09:00") %></li>
				<li class="list-group-item"><%= apontamento("09:15") %></li>
				<li class="list-group-item"><%= apontamento("09:30") %></li>
				<li class="list-group-item"><%= apontamento("09:45") %></li>
				<li class="list-group-item"><%= apontamento("10:00") %></li>
				<li class="list-group-item"><%= apontamento("10:15") %></li>
				<li class="list-group-item"><%= apontamento("10:30") %></li>
				<li class="list-group-item"><%= apontamento("10:45") %></li>
				<li class="list-group-item"><%= apontamento("11:00") %></li>
				<li class="list-group-item"><%= apontamento("11:15") %></li>
				<li class="list-group-item"><%= apontamento("11:30") %></li>
				<li class="list-group-item"><%= apontamento("11:45") %></li>
			</ul><!-- /.list-group -->
		</div><!-- /col -->
		<div class="col-lg-6 col-md-6">
			<ul class="list-group">
			<li class="list-group-item disabled"><strong>TARDE</strong></li>
			  <li class="list-group-item"><%= apontamento("13:00") %></li>
			  <li class="list-group-item"><%= apontamento("13:15") %></li>
			  <li class="list-group-item"><%= apontamento("13:30") %></li>
			  <li class="list-group-item"><%= apontamento("13:45") %></li>
			  <li class="list-group-item"><%= apontamento("14:00") %></li>
			  <li class="list-group-item"><%= apontamento("14:15") %></li>
			  <li class="list-group-item"><%= apontamento("14:30") %></li>
			  <li class="list-group-item"><%= apontamento("14:45") %></li>
			  <li class="list-group-item"><%= apontamento("15:00") %></li>
			  <li class="list-group-item"><%= apontamento("15:15") %></li>
			  <li class="list-group-item"><%= apontamento("15:30") %></li>
			  <li class="list-group-item"><%= apontamento("15:45") %></li>
			  <li class="list-group-item"><%= apontamento("16:00") %></li>
			  <li class="list-group-item"><%= apontamento("16:15") %></li>
			  <li class="list-group-item"><%= apontamento("16:30") %></li>
			  <li class="list-group-item"><%= apontamento("16:45") %></li>
			  <li class="list-group-item"><%= apontamento("17:00") %></li>
			  <li class="list-group-item"><%= apontamento("17:15") %></li>
			  <li class="list-group-item"><%= apontamento("17:30") %></li>
			  <li class="list-group-item"><%= apontamento("17:45") %></li>
			  <li class="list-group-item"><%= apontamento("18:00") %></li>
			  <li class="list-group-item"><%= apontamento("18:15") %></li>
        <li class="list-group-item"><%= apontamento("18:30") %></li>
        <li class="list-group-item"><%= apontamento("18:45") %></li>
        <li class="list-group-item"><%= apontamento("19:00") %></li>
			</ul>
		</div>
	</div><!-- /row -->

app/views/attends/_new.html.erb
<!-- Modal -->
  <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="modal_label_listagem"><%= t('New') %> <%= t('attend') %></h4>
        </div>
        <div class="modal-body">          
          <div id="formulario" >
            <%= render partial: "form" %>
          </div><!-- /formulario-->
        </div><!-- /.modal-body -->
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        </div>
      </div>
  </div><!-- /.modal-dialog -->

app/views/attends/diasel.js.erb
$("#lista-horarios").html("<%= escape_javascript render(partial: "listagem", locals: {attends: @attends}) %>");