config/routes.rb
Rails.application.routes.draw do
  resources :products do 
    get "delete"
  end

  resources :attends do
    member do
      get 'export'
    end
  end

  resources :exams
  resources :patients
  resources :requesters
  resources :clinics
  get 'welcome/index'

  get "/qual_dia" => 'attends#diasel', as: 'qual_dia'

  get "/etiquetas" => 'attends#etiquetas'
  get "/print" => 'attends#print'

  devise_for :users, :path_prefix => 'my'
  resources :users

  root 'attends#index'

end

app/views/layouts/_nav.html.erb
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="menu">
			<ul class="nav navbar-nav">
				<li class="<%= active?('attends')%>"><%= link_to "AGENDA", attends_path %></li>
				<li class="<%= active?('clinics')%>"><%= link_to "CLÍNICAS", clinics_path %></li>
				<li class="<%= active?('requesters')%>"><%= link_to "SOLICITANTES", requesters_path %></li>
				<li class="<%= active?('exams')%>"><%= link_to "EXAMES", exams_path %></li>				
				<li class="<%= active?('patients')%>"><%= link_to "PACIENTES", patients_path %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
		        <li>
			        <% @user = User.find(current_user.id) %>
					<%= simple_form_for(@user, :html=> { class: 'navbar-form' }) do |f| %>
					    <div class="form-group">
					  <%= f.association :clinic, :input_html => {:onchange => '$(this.form).submit();', :class => 'form-control' }, :label => false, label_method: :fantasy_name, value_method: :id, prompt: t('select') %>
					  </div>
					<% end %>
		        </li>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-cog"></span></a>
		          <ul class="dropdown-menu">
		            <li><%= link_to edit_user_registration_path do %><span class="glyphicon glyphicon-user"></span> <%= current_user.email %><% end %></li>
		            <li><%= link_to welcome_index_path do %><span class="glyphicon glyphicon-info-sign"></span> Info<% end %></li>
		            <li role="separator" class="divider"></li>
		            <li><%= link_to destroy_user_session_path, method: :delete do %><span class="glyphicon glyphicon-log-out"></span> Sair <% end %></li>
		          </ul>
		        </li>
		    </ul>
		</div><!-- /.navbar-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>RADIODON</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'application/favicon' %>
</head>
<body>
  <!-- Flash messages -->
  <% flash.each do |type, message| %>
  	  <div id="flash-message-wrapper" class="auto-close-alert alert <%= bootstrap_class_for(type) %> alert-dismissible fade in" role="alert">
        <div class="container">
  	       <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  	        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> <%= message %>
        </div><!-- /container -->
  	  </div><!-- /#flash-message-wrapper -->
  <% end %>

<nav class="navbar navbar-inverse" role="navigation">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</button>
		    <%= link_to root_path, :class => 'navbar-brand logo-custom' do %>
          <%= image_tag('radiodon-logo2.png') %>
		    <% end %>
		</div>
			<%= if user_signed_in?
					render partial: "layouts/nav"
				end
			%>
	</div><!-- /.container -->
</nav>
<div class="container">
<%= yield %>
<hr>
</div><!-- /container -->
</body>
</html>